### ISSUE TITLE
Typo in fan on logic?

### ISSUE THREAD

**Issue by kkorach** [napalmcsr/Hubitat_Napalmcsr#1]
Enjoying your app so far and its helping me learn how to go beyond the rule machine with hubitat.  Our fan kept coming on after the humidity decreased below the target threshold and I think it comes from the conditional on line 170

```
    if (((state.HumidityChangeRate>HumidityIncreaseRate)||state.OverThreshold) && (FanSwitch.currentValue("switch") == "off")&&!modeStop)
```

Should it be `&&state.overThreshold`?  In my case the humidity was dropping, below the target, but above the threshold.

**Comment by napalmcsr** [comment]
I am trying to have the fan be on if you are above the threshold, so I would think this is correct.
